name: SonarCloud

on:
  push:
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Run Tests with Coverage
        run: |
          dotnet build
          dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=TestResults/

      - name: Prepare coverage report
        run: |
            reportgenerator \
            -reports:TestResults//coverage.cobertura.xml \
            -targetdir:coverage-report \
            -reporttypes:Cobertura
        env:
            PATH: ${{ env.PATH }}:/home/runner/.dotnet/tools

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master          
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}