name: SonarCloud
on:
  push:
    branches:
      - master
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable for UTF-8
        run: |
          export LANG="en_US.UTF-8"
          export LC_ALL="en_US.UTF-8"
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0

      - name: Install SonarCloud Scanner
        run: dotnet tool install --global dotnet-sonarscanner
      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"luanapettersm_ProjectPortfolio" /o:"luanapettersm" /d:sonar.login=${{ secrets.SONAR_TOKEN }}
          dotnet build
          dotnet test --collect:"XPlat Code Coverage"
          dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
