name: SonarCloud

on:
  push:
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Run unit tests
        run: dotnet test --verbosity normal
      - name: Run Tests with Coverage
        run: |
          dotnet build
          dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=TestResults/

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=luanapettersm_ProjectPortfolio
            -Dsonar.organization=luanapettersm
            -Dsonar.cs.opencover.reportsPaths=TestResults/coverage.opencover.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}          
