name: SonarCloud

on:
  push:
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore
      
      - name: Executar testes com cobertura
        run: |
          dotnet build
          dotnet test --collect:"XPlat Code Coverage" --results-directory TestResults

      - name: Verificar arquivos gerados
        run: ls TestResults

      - name: Instalar ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
      
      - name: Preparar relatório de cobertura
        run: |
            reportgenerator \
            -reports:TestResults//*.xml \
            -targetdir:coverage-report \
            -reporttypes:Cobertura
        env:
            PATH: ${{ env.PATH }}:/home/runner/.dotnet/tools

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}